import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../styles/terminal.css";

const orbitron = localFont({
  src: "../fonts/Orbitron-Regular.ttf",
  variable: "--font-orbitron",
  display: "swap",
});

const vcr = localFont({
  src: "../fonts/VCR_OSD_MONO_1.001.ttf",
  variable: "--font-vcr",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${orbitron.variable} ${vcr.variable} antialiased`}>
        <h1
          style={{
            fontFamily: "var(--font-orbitron)",
            fontSize: "3rem",
            textTransform: "uppercase",
          }}
        >
          ORBITRON FONT
        </h1>

        <h2
          style={{
            fontFamily: "var(--font-vcr)",
            fontSize: "2rem",
            letterSpacing: "0.05em",
          }}
        >
          VCR OSD MONO
        </h2>
        {children}
      </body>
    </html>
  );
}
